"use client";
import { useEffect, useState } from "react";

type Employee = { id: number; name: string };
type CaseItem = { id: number; companyName: string; summary: string; employeeId: number; employeeName: string; progress: number; updatedAt: string; completedAt?: string; bonusTwd: number };
type Dashboard = { month: string; completedCount: number; bonusTotal: number; bonusPerCase: number; employees: (Employee & { completedCount: number; bonusTotal: number })[] };

export default function CasesDashboard({ onOpenWizard }: { onOpenWizard: (item: CaseItem) => void }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [cases, setCases] = useState<CaseItem[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [history, setHistory] = useState<CaseItem[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [currentUser, setCurrentUser] = useState(""); const [showNew, setShowNew] = useState(false); const [draft, setDraft] = useState({ companyName: "", summary: "", employeeId: "" }); const [filters, setFilters] = useState({ month: "", employeeId: "", company: "" });
  const load = async () => { setLoading(true); setError(""); try { const q = new URLSearchParams({ history: "1" }); if (filters.month) q.set("month", filters.month); if (filters.employeeId) q.set("employeeId", filters.employeeId); if (filters.company) q.set("company", filters.company); const [a, b, c] = await Promise.all([fetch("/api/cases/dashboard"), fetch("/api/cases"), fetch(`/api/cases?${q}`)]); if (!a.ok || !b.ok || !c.ok) throw new Error("案件資料暫時無法載入，請稍後再試。"); const d = await a.json() as Dashboard; const active = await b.json() as { cases: CaseItem[]; employees: Employee[] }; const completed = await c.json() as { cases: CaseItem[] }; setDashboard(d); setCases(active.cases); setEmployees(active.employees); setHistory(completed.cases); setCurrentUser(v => v || active.employees[0]?.name || ""); } catch (e) { setError(e instanceof Error ? e.message : "案件資料暫時無法載入。"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [filters.month, filters.employeeId, filters.company]);
  const update = async (id: number, body: object, confirmText: string) => { if (!confirm(confirmText)) return; try { const r = await fetch(`/api/cases/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) throw new Error("更新失敗，請再試一次。"); await load(); } catch (e) { setError(e instanceof Error ? e.message : "更新失敗"); } };
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const r = await fetch("/api/cases", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...draft, employeeId: Number(draft.employeeId) }) }); if (!r.ok) throw new Error("建立失敗，請檢查欄位。"); setDraft({ companyName: "", summary: "", employeeId: "" }); setShowNew(false); await load(); } catch (x) { setError(x instanceof Error ? x.message : "建立失敗"); } };
  return <main className="cases-main"><header className="cases-header"><div><p className="eyebrow">工商案件管理</p><h1>案件首頁</h1><p>公司受控環境使用，員工以姓名選擇追蹤。本站為 Sites 私人站。</p></div><label>目前使用者<select value={currentUser} onChange={e => setCurrentUser(e.target.value)}>{employees.map(e => <option key={e.id}>{e.name}</option>)}</select></label></header>{error && <p className="case-error">{error}</p>}{loading && <p className="case-loading">正在讀取案件資料…</p>}
    {dashboard && <section className="metric-grid"><article><span>本月已結案</span><strong>{dashboard.completedCount} 家</strong></article><article><span>每件結案獎金</span><strong>NT$ {dashboard.bonusPerCase}</strong></article><article><span>本月獎金合計</span><strong>NT$ {dashboard.bonusTotal}</strong></article></section>}
    <section className="case-panel"><h2>本月員工結案與獎金</h2><div className="employee-grid">{dashboard?.employees.map(e => <div key={e.id}><strong>{e.name}</strong><span>{e.completedCount} 件 · NT$ {e.bonusTotal}</span></div>)}</div></section>
    <section className="case-panel"><div className="panel-heading"><div><h2>進行中案件</h2><p>範例工程有限公司為正式進行中資料；其餘範例均明示為示意。</p></div><button className="primary" onClick={() => setShowNew(!showNew)}>{showNew ? "收起表單" : "新建案件"}</button></div>{showNew && <form className="new-case" onSubmit={create}><input required placeholder="公司名稱" value={draft.companyName} onChange={e => setDraft({ ...draft, companyName: e.target.value })}/><input required placeholder="案件摘要" value={draft.summary} onChange={e => setDraft({ ...draft, summary: e.target.value })}/><select required value={draft.employeeId} onChange={e => setDraft({ ...draft, employeeId: e.target.value })}><option value="">選擇承辦人</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select><button className="primary">建立並保存</button></form>}<div className="case-list">{!loading && !cases.length ? <p>目前沒有進行中案件。</p> : cases.map(item => <article key={item.id}><div><h3>{item.companyName}</h3><p>{item.summary}</p><small>更新日期：{new Date(item.updatedAt).toLocaleDateString("zh-TW")}</small></div><label>承辦人<select value={item.employeeId} onChange={e => void update(item.id, { employeeId: Number(e.target.value) }, "確定變更承辦人？")}>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="progress"><span style={{ width: `${item.progress}%` }}/><small>{item.progress}%</small></div><div className="case-actions"><button className="secondary" onClick={() => onOpenWizard(item)}>進入三步驟流程</button><button className="primary" onClick={() => void update(item.id, { action: "complete" }, "確定將此案件結案？結案後會移入歷史，並計入 NT$500 獎金。")}>已結案</button></div></article>)}</div></section>
    <section className="case-panel"><h2>結案歷史（示意案例已標示）</h2><div className="history-filters"><input type="month" value={filters.month} onChange={e => setFilters({ ...filters, month: e.target.value })}/><select value={filters.employeeId} onChange={e => setFilters({ ...filters, employeeId: e.target.value })}><option value="">全部員工</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select><input placeholder="公司名查詢" value={filters.company} onChange={e => setFilters({ ...filters, company: e.target.value })}/></div>{!loading && !history.length ? <p>沒有符合條件的結案歷史。</p> : <div className="history-list">{history.map(item => <article key={item.id}><div><strong>{item.companyName}</strong><span>{item.employeeName} · 結案日 {item.completedAt ? new Date(item.completedAt).toLocaleDateString("zh-TW") : "—"} · 獎金 NT$ {item.bonusTwd}</span></div><button className="secondary" onClick={() => void update(item.id, { action: "restore" }, "確定取消結案並恢復為進行中？此操作可重新結案。")}>取消結案／恢復進行中</button></article>)}</div>}</section></main>;
}
