"use client";

import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Check, Download, Eye, FileText, Trash2, UploadCloud } from "lucide-react";
import CasesDashboard from "./cases-dashboard";

type SlotKey = "name_reservation" | "identity" | "land_title" | "house_tax" | "passbook" | "building_consent" | "lease" | "floor_plan" | "other";
type Slot = { key: SlotKey; phase: string; title: string; purpose: string; required: boolean; multiple?: boolean; reuse?: string };
type SlotFiles = Record<SlotKey, File[]>;
type LinkTarget = "land_title" | "building_consent" | "floor_plan";
type SourceLink = { sourceSlot: "lease"; targetSlot: LinkTarget; sourceFileName: string; pageRange: string; status: "suggested" | "confirmed" | "dismissed"; confidence: "較高" | "低" };
type OutputKey = "company_application" | "registration_form" | "registration_card_city" | "registration_card_return" | "articles" | "shareholder" | "director" | "aml" | SlotKey;

const slots: Slot[] = [
  { key: "name_reservation", phase: "名稱預查", title: "名稱預查核定書", purpose: "核對公司名稱與預查編號", required: true },
  { key: "identity", phase: "市政府設立", title: "身分證正反面", purpose: "確認負責人身分", required: true, multiple: true, reuse: "後續防洗錢文件將沿用" },
  { key: "land_title", phase: "市政府設立", title: "土地權狀", purpose: "確認設立地址權利關係", required: true },
  { key: "house_tax", phase: "市政府設立", title: "房屋稅單", purpose: "核對建物資料", required: true, reuse: "後續將沿用" },
  { key: "passbook", phase: "市政府設立", title: "籌備處存摺", purpose: "核對資本額存入資料", required: true },
  { key: "building_consent", phase: "市政府設立", title: "建物所有人同意書", purpose: "確認地址使用同意", required: false, reuse: "後續將沿用" },
  { key: "lease", phase: "國稅局接續", title: "租約", purpose: "供國稅局營業地址審核", required: true },
  { key: "floor_plan", phase: "國稅局接續", title: "商辦平面圖", purpose: "說明營業空間配置", required: false },
  { key: "other", phase: "國稅局接續", title: "其他文件", purpose: "補充審核所需資料", required: false },
];
const emptyFiles = (): SlotFiles => Object.fromEntries(slots.map((slot) => [slot.key, []])) as unknown as SlotFiles;
const initialForm = { company: "範例工程有限公司", representative: "王小明", nationalId: "A123456789", precheck: "115004506", approval: "115/01/22", expiry: "115/07/21", contactAddress: "臺北市中正區範例路1號", registrationAddress: "", capital: "1,000,000" };
const initialBusiness = ["E599010 配管工程業", "E601010 電器承裝業", "E603050 自動控制設備工程業", "E603090 照明設備安裝工程業", "IG03010 能源技術服務業", "ZZ99999 除許可業務外，得經營法令非禁止或限制之業務"];
const allowed = new Set(["pdf", "jpg", "jpeg", "png", "doc", "docx"]);
const bytes = (value: number) => value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`;
const ext = (file: File) => file.name.split(".").pop()?.toLowerCase() ?? "";
const supported = (file: File) => allowed.has(ext(file));
export const xmlEscape = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[char]!);
const p = (line: string, bold = false) => `<w:p><w:r>${bold ? "<w:rPr><w:b/></w:rPr>" : ""}<w:t xml:space="preserve">${xmlEscape(line)}</w:t></w:r></w:p>`;
export const wordXml = (title: string, lines: string[]) => `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?mso-application progid="Word.Document"?><w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"><w:fonts><w:defaultFonts w:ascii="DFKai-SB" w:h-ansi="DFKai-SB" w:fareast="標楷體"/></w:fonts><w:styles><w:style w:type="paragraph" w:default="on" w:styleId="Normal"><w:rPr><w:rFonts w:ascii="DFKai-SB" w:h-ansi="DFKai-SB" w:fareast="標楷體"/></w:rPr></w:style></w:styles><w:body>${p(title, true)}${lines.map(line => p(line)).join("")}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:wordDocument>`;
export const downloadXml = (name: string, xml: string) => downloadBlob(new Blob([xml], { type: "application/xml;charset=utf-8" }), `${name}.xml`);
const downloadBlob = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };
const downloadOriginalFile = (file: File) => downloadBlob(file, file.name);

const outputLabels: { key: OutputKey; label: string }[] = [
  { key: "company_application", label: "公司設立登記申請書" }, { key: "registration_form", label: "公司設立登記表" }, { key: "registration_card_city", label: "登記事項卡（市政府留存）" }, { key: "registration_card_return", label: "登記事項卡（蓋章寄回客戶）" }, { key: "articles", label: "公司章程" }, { key: "shareholder", label: "股東同意書" }, { key: "director", label: "董事願任同意書" }, { key: "aml", label: "防制洗錢確認書" },
  ...slots.map(slot => ({ key: slot.key as OutputKey, label: `${slot.title}（原始附件）` })),
];

export default function Home() {
  const [view, setView] = useState<"dashboard" | "wizard">("dashboard"); const [step, setStep] = useState(1);
  const [files, setFiles] = useState<SlotFiles>(emptyFiles); const [links, setLinks] = useState<SourceLink[]>([]); const [recognising, setRecognising] = useState(false); const [recognitionDone, setRecognitionDone] = useState(false);
  const refs = useRef<Record<SlotKey, HTMLInputElement | null>>({} as Record<SlotKey, HTMLInputElement | null>);
  const [form, setForm] = useState(initialForm);
  const [business, setBusiness] = useState(initialBusiness);
  const linkFor = (key: SlotKey) => links.find(link => link.targetSlot === key && link.status === "confirmed");
  const validFiles = (key: SlotKey) => files[key].filter(supported);
  const received = (key: SlotKey) => validFiles(key).length > 0 || Boolean(linkFor(key));
  const requiredMissing = slots.filter(slot => slot.required && !received(slot.key));
  const canStart = validFiles("name_reservation").length > 0 && validFiles("identity").length > 0;
  const addFiles = (key: SlotKey, incoming: FileList | null) => { if (!incoming?.length) return; const slot = slots.find(item => item.key === key)!; const chosen = Array.from(incoming); setFiles(current => ({ ...current, [key]: slot.multiple ? chosen.slice(0, 2) : chosen.slice(0, 1) })); setRecognitionDone(false); };
  const drop = (event: DragEvent<HTMLDivElement>, key: SlotKey) => { event.preventDefault(); addFiles(key, event.dataTransfer.files); };
  const remove = (key: SlotKey, index: number) => setFiles(current => ({ ...current, [key]: current[key].filter((_, i) => i !== index) }));
  const previewFile = (file: File) => { const url = URL.createObjectURL(file); window.open(url, "_blank", "noopener"); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); };
  const makeSuggestions = () => { const lease = files.lease[0]; if (!lease || ext(lease) !== "pdf") return; const high = /權狀|同意書|平面圖|合併|多頁/.test(lease.name); setLinks(current => ["land_title", "building_consent", "floor_plan"].map(targetSlot => current.find(link => link.targetSlot === targetSlot) ?? ({ sourceSlot: "lease", targetSlot: targetSlot as LinkTarget, sourceFileName: lease.name, pageRange: "待確認", status: "suggested", confidence: high ? "較高" : "低" })));
  };
  const startRecognition = () => { if (!canStart || recognising) return; setRecognising(true); setRecognitionDone(false); window.setTimeout(() => { setRecognising(false); setRecognitionDone(true); makeSuggestions(); }, 600); };
  const updateLink = (target: LinkTarget, patch: Partial<SourceLink>) => setLinks(current => current.map(link => link.targetSlot === target ? { ...link, ...patch } : link));
  const sourceFile = (key: SlotKey) => validFiles(key)[0] ?? (linkFor(key) ? validFiles("lease")[0] : undefined);
  const formComplete = Object.values(form).every(value => Boolean(value) && value !== "待補") && business.length === 6 && business.every(Boolean);
  const articleLines = [
    `第一條　本公司依照公司法規定組織之定名為${form.company}。`, `第二條　本公司所營事業如下：`, ...business.map((item, i) => `${i + 1}. ${item}`), `第三條　本公司所在地設於台中市，必要時得在國內外設立分公司。`, `第四條　本公司之公告方法依照公司法第廿八條規定辦理。`, `第五條　本公司資本總額定為新台幣${form.capital}元整，全額繳足，各股東姓名、出資額如下：${form.representative}｜${form.capital}元整。`, "第五條之一　本公司為業務需要得對外保證。", "第六條　股東非得其他股東表決權過半數之同意，不得以其出資之全部或一部，轉讓於他人。董事非得其他股東表決權三分之二以上之同意，不得以其出資之全部或一部，轉讓於他人。", "第七條　本公司股東每出資新台幣壹仟元，有一表決權。", "第八條　本公司重要事項除公司法另有規定外經全體股東同意行之。", "第九條　本公司置董事一人執行業務並對外代表公司。", "第十條　本公司得設經理人，其委任、解任及報酬，依照公司法第廿九條規定辦理。", "第十一條　本公司每會計年度終了，董事應編造：(一)營業報告書、(二)財務報表、(三)盈餘分派或虧損撥補之議案送請各股東承認。", "第十二條　董事之報酬得於章程內訂明或依特約另定之。", "第十三條　公司年度如有獲利，應提撥新台幣壹仟元為員工酬勞。但公司尚有累積虧損時，應預先保留彌補數額。", "第十四條　本公司之盈餘及虧損按照各股東出資比例分派之。公司年度總決算如有盈餘，應先提繳稅款，彌補累積虧損，次提10%為法定盈餘公積，但法定盈餘公積金已達資本總額時，不在此限。其餘除派付股息外，如尚有盈餘，再由股東同意分配股東紅利。", "第十五條　本章程未盡事宜悉依照公司法及有關法令之規定辦理。", "第十六條　本章程訂立於民國＿＿年＿＿月＿＿日。", `公司名稱：${form.company}`, `董事：${form.representative}`
  ];
  const doc = (key: OutputKey): [string, string[]] => key === "articles" ? [`${form.company}章程`, articleLines] : key === "shareholder" ? [`${form.company}股東同意書`, [`茲同意設立${form.company}，訂定公司章程，並選任${form.representative}為董事。`, `股東姓名：${form.representative}`, "公司大章：＿＿＿＿＿＿＿＿", "＿＿＿＿＿＿＿＿", "＿＿＿＿＿＿＿＿", "＿＿＿＿＿＿＿＿", "＿＿＿＿＿＿＿＿", "日期：民國＿＿年＿＿月＿＿日", "提醒：日期為存入資本額日期，請先留空"]] : key === "director" ? ["董事願任同意書", [`本人同意擔任${form.company}董事。`, `立同意書人：${form.representative}`, "親簽：＿＿＿＿＿＿＿＿", "日期：民國＿＿年＿＿月＿＿日", "提醒：日期為存入資本額日期，請先留空"]] : ["防制洗錢確認書", [`姓名：${form.representative}`, `身分證字號：${form.nationalId}`, `地址：${form.contactAddress}`, "職業：＿＿＿＿＿＿＿＿　電話：＿＿＿＿＿＿＿＿　Email：＿＿＿＿＿＿＿＿", "是否為 PEP：＿＿＿＿＿＿＿＿　資金來源：＿＿＿＿＿＿＿＿", "證明文件：＿＿＿＿＿＿＿＿", "身分證正反面附件：已由 Step 1 上傳文件沿用。", "親簽：＿＿＿＿＿＿＿＿", "日期：民國＿＿年＿＿月＿＿日", "提醒：日期可填寫簽名當天日期"]];
  const output = (key: OutputKey) => {
    if (slots.some(slot => slot.key === key)) { const keySlot = key as SlotKey; const originals = validFiles(keySlot); if (originals.length) originals.forEach(downloadOriginalFile); else { const file = sourceFile(keySlot); if (file) downloadOriginalFile(file); } return; }
    const [name, lines] = doc(key); downloadXml(name, wordXml(name, lines));
  };
  const outputState = (key: OutputKey) => {
    if (["company_application", "registration_form", "registration_card_city", "registration_card_return"].includes(key)) return { ready: false, reason: "待提供正式範本" };
    if (slots.some(slot => slot.key === key)) { const slot = slots.find(item => item.key === key)!; const keySlot = key as SlotKey; const link = linkFor(keySlot); const count = validFiles(keySlot).length; return sourceFile(keySlot) ? { ready: true, reason: link ? `包含於租約：${link.sourceFileName}（第 ${link.pageRange} 頁）` : count > 1 ? `可下載 ${count} 份原始附件` : "可下載原始附件" } : { ready: false, reason: slot.required ? "待補" : "尚未提供" }; }
    if (key === "articles") return { ready: formComplete, reason: formComplete ? "可產出 Word XML" : "待補公司基本資料" };
    if (key === "aml") return { ready: Boolean(form.representative && form.nationalId && form.contactAddress), reason: "待補負責人、身分證或地址" };
    return { ready: Boolean(form.company && form.representative && form.capital), reason: "待補公司、股東或出資資料" };
  };
  if (view === "dashboard") return <CasesDashboard onOpenWizard={item => { setForm(item.companyName === "範例工程有限公司" ? initialForm : { company: item.companyName, representative: "", nationalId: "", precheck: "", approval: "", expiry: "", contactAddress: "", registrationAddress: "", capital: "" }); setBusiness(item.companyName === "範例工程有限公司" ? initialBusiness : []); setStep(1); setView("wizard"); }} />;
  return <main><button className="secondary back-dashboard" onClick={() => setView("dashboard")}>返回案件總覽</button><header className="hero"><div><p className="eyebrow">公司設立文件流程</p><h1>三步完成送件準備</h1><p>請先上傳來源文件；系統產出書件不需要上傳。</p></div></header><nav className="wizard">{["來源文件", "公司資料", "產出與下載"].map((label, i) => <div key={label} className={step === i + 1 ? "active" : step > i + 1 ? "complete" : ""}><span>{i + 1}</span>{label}</div>)}</nav>
    {step === 1 && <section className="stage"><div className="stage-heading"><div><p className="eyebrow">STEP 1</p><h2>來源文件</h2><p>每份文件各自上傳、預覽、替換或刪除。支援 PDF、JPG、JPEG、PNG、DOC、DOCX。</p></div></div>{["名稱預查", "市政府設立", "國稅局接續"].map(phase => <section className="source-phase" key={phase}><h3>{phase}</h3>{slots.filter(slot => slot.phase === phase).map(slot => <div className="slot-card" key={slot.key}><div><strong>{slot.title} {slot.required ? <em>必填</em> : <em className="optional">選填</em>}</strong><small>{slot.purpose}{slot.reuse ? `｜${slot.reuse}` : ""}</small>{linkFor(slot.key) && <small className="linked">已收到（包含在租約檔案中）：{linkFor(slot.key)!.sourceFileName}，第 {linkFor(slot.key)!.pageRange} 頁</small>}</div><div className="slot-drop" onDragOver={event => event.preventDefault()} onDrop={event => drop(event, slot.key)}><input ref={node => { refs.current[slot.key] = node; }} type="file" multiple={slot.multiple} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={(event: ChangeEvent<HTMLInputElement>) => addFiles(slot.key, event.target.files)} /><button className="secondary small" onClick={() => refs.current[slot.key]?.click()}><UploadCloud size={15}/>選擇或拖曳</button><span>{slot.multiple ? "最多 2 份" : "限 1 份"}</span></div><div className="slot-files">{files[slot.key].map((file, index) => <div className="file-row" key={`${file.name}-${index}`}><FileText size={18}/><div><strong>{file.name}</strong><span>{ext(file).toUpperCase()}・{bytes(file.size)}・{supported(file) ? "已收到" : "不支援，需人工確認"}</span></div><button aria-label="預覽原檔" onClick={() => previewFile(file)}><Eye size={16}/></button><button aria-label="替換檔案" onClick={() => refs.current[slot.key]?.click()}>替換</button><button aria-label="刪除檔案" onClick={() => remove(slot.key, index)}><Trash2 size={16}/></button></div>)}{!files[slot.key].length && !linkFor(slot.key) && <small className="pending">{slot.required ? "待補" : "尚未提供"}</small>}</div></div>)}</section>)}
      {links.some(link => link.status !== "dismissed") && <section className="link-suggestions"><h3>合併檔關聯建議</h3><p>示範辨識／未實際執行 OCR，需人工確認。未確認前不視為已收到。</p>{links.filter(link => link.status !== "dismissed").map(link => <div key={link.targetSlot}><strong>{slots.find(slot => slot.key === link.targetSlot)!.title}</strong><span>建議來源：{link.sourceFileName}（{link.confidence}信心）</span><input aria-label={`${link.targetSlot} 頁碼範圍`} value={link.pageRange} onChange={event => updateLink(link.targetSlot, { pageRange: event.target.value })} placeholder="例如 3-5" disabled={link.status === "confirmed"}/>{link.status === "confirmed" ? <><button className="secondary small" onClick={() => updateLink(link.targetSlot, { status: "suggested" })}>取消關聯</button><button className="secondary small" onClick={() => previewFile(files.lease[0])}><Eye size={15}/>預覽來源</button></> : <><button disabled={!/^\d+(?:-\d+)?$/.test(link.pageRange)} className="primary small" onClick={() => updateLink(link.targetSlot, { status: "confirmed" })}>確認關聯</button><button className="secondary small" onClick={() => updateLink(link.targetSlot, { status: "dismissed" })}>取消</button></>}</div>)}</section>}
      {!canStart && <p className="recognition-note"><AlertTriangle size={17}/>開始辨識與繼續至少需要名稱預查核定書及身分證。</p>}{requiredMissing.length > 0 && <p className="recognition-note">其他必填待補：{requiredMissing.map(slot => slot.title).join("、")}；可先繼續，待補狀態會保留至 Step 3。</p>}<footer className="stage-actions"><button className="primary" disabled={!canStart || recognising} onClick={startRecognition}>{recognising ? "辨識中…" : "開始辨識"}</button><button className="secondary" disabled={!canStart} onClick={() => setStep(2)}>先繼續填寫 <ArrowRight size={16}/></button></footer>{recognitionDone && <p className="completion-note"><Check size={17}/>已完成文件狀態檢查；不支援格式已標示需人工確認。</p>}</section>}
    {step === 2 && <section className="stage"><p className="eyebrow">STEP 2</p><h2>公司資料</h2><p className="expiry-alert"><AlertTriangle size={18}/><span><strong>名稱保留期限已屆滿</strong>名稱保留期限已屆滿，送件前請先確認是否仍可使用或需重新預查。</span></p><div className="form-grid">{(["company", "representative", "nationalId", "precheck", "approval", "expiry", "contactAddress", "registrationAddress", "capital"] as (keyof typeof form)[]).map(key => <label key={key}><span>{{ company: "公司名稱", representative: "負責人", nationalId: "身分證字號", precheck: "預查編號", approval: "核准日期", expiry: "預查期限", contactAddress: "聯絡地址", registrationAddress: "公司所在地", capital: "資本額" }[key]}</span><input value={form[key]} onChange={event => setForm(current => ({ ...current, [key]: event.target.value }))}/></label>)}</div><section className="business-section"><h3>營業項目（6 項）</h3>{business.map((item, index) => <div className="business-list" key={`${index}-${item}`}><input value={item} onChange={event => setBusiness(current => current.map((entry, i) => i === index ? event.target.value : entry))}/><button className="secondary small" onClick={() => setBusiness(current => current.filter((_, i) => i !== index))}>刪除</button></div>)}<button className="secondary small" onClick={() => setBusiness(current => [...current, ""])}>新增營業項目</button></section><footer className="stage-actions"><button className="secondary" onClick={() => setStep(1)}><ArrowLeft size={16}/>上一步</button><button className="primary" onClick={() => setStep(3)}>前往產出</button></footer></section>}
    {step === 3 && <section className="stage"><p className="eyebrow">STEP 3</p><h2>產出與下載</h2><p>系統產出四份 Word XML；來源附件一律下載原始檔並保留原檔名。</p><div className="output-list">{outputLabels.map(item => { const state = outputState(item.key); return <div className="output-row" key={item.key}><div><span className={state.ready ? "output-ready" : "output-pending"}>{state.ready ? <Check size={15}/> : <AlertTriangle size={15}/>}</span><strong>{item.label}</strong><small>{state.reason}</small></div><button disabled={!state.ready} className={state.ready ? "download ready" : "download"} onClick={() => output(item.key)}><Download size={16}/>{state.ready ? "下載" : state.reason}</button></div>; })}</div><footer className="stage-actions"><button className="secondary" onClick={() => setStep(2)}><ArrowLeft size={16}/>上一步</button></footer></section>}</main>;
}
